# .github/workflows/terraform.yml
name: Terraform + Docker (final)

on:
  workflow_dispatch:   # Tu le lances à la main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Installe Docker (obligatoire pour le provider kreuzwerker/docker)
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Initialise et applique Terraform
      - name: Terraform Init & Apply
        working-directory: ./terraform
        run: |
          terraform init
          terraform apply -auto-approve

      - name: Résultat
        run: echo "Conteneur lancé avec succès via Terraform + Docker !"